// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('My first test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('My first test', async function() {
    await driver.get("https://preview.viasat.com/about-us/?v=2")
    await driver.wait(until.elementLocated(By.linkText("Change Region")), 30000)
    await driver.close()
  })
})