# This is a basic workflow to help you get started with Actions

name: Udemy Gatsby

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master and develop branch
on:
  push:
    branches:
      - master
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs like "build"
  lint:
    steps:
    
      - name: Run ESLint
  # You may pin to the exact commit or the version.
  # uses: stefanoeb/eslint-action@0b532bcd98dbed80a59071fa8986fcf1b1715be4
         uses: stefanoeb/eslint-action@1.0.2
        with:
    # Blob of files to lint
          files: ./myfirsttest.spec.js
  
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: |
          npm install
          npm install -g gatsby-cli
          gatsby serve &
          sleep 10
          curl "http://localhost:9000" | grep -q "Gatsby"
