# This is a basic workflow to help you get started with Actions

name: Udemy Gatsby

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master and develop branch
on:
  push:
    branches:
      - master
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: ./node_modules/.bin/eslint --init
    - name: Run ESLint
      run:  eslint . --ext .js,.jsx,.ts,.tsx