# This is a basic workflow to help you get started with Actions

name: Udemy Gatsby

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master and develop branch
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: ./node_modules/.bin/eslint ./myfirsttest.spec.js
    - name: Gatsby Publish
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: enriikke/gatsby-gh-pages-action@v2.1.1
    - with:
      access-token: ${{ secrets.GITHUB_TOKEN }}
    